sh scripts/shell_scripts/gradual/v2_run_for_bnlearn_search_every_step/asia/submit_asia.sh
sh scripts/shell_scripts/gradual/v2_run_for_bnlearn_search_every_step/sachs/submit_sachs.sh
sh scripts/shell_scripts/gradual/v2_run_for_bnlearn_search_every_step/child/submit_child.sh
