qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch1.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch2.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch3.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch4.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch5.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch6.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch7.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch8.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch9.sh
qsub scripts/shell_scripts/gradual/v2_run_for_bnlearn/asia/asia_batch10.sh
